In [1]:
import pandas as pd
dados = pd.read_csv("legal_claims.csv")

In [15]:
dados.head(100)

,LAWSUIT NUMBER,AREA,STATUS,PLAINTIFF OR DEFENDANT,CONTRACT TYPE,COMPANY,SUPPLIER NAME,TYPE OF POSITION,CITY SUBSIDIARIES,PHASE,...,DISMISSAL DATE,ID PLANTIFF'S LAWYER,CLAIM START DATE,CLOSE DATE,CLAIM AMOUNT,AMOUNT PAID,PROVISION VALUE,RISK VALUE,RISK,TYPE OF CLOSING CLAIM
0,0000000-00.2010.0.00.0094,TAX,CLOSED,DEFENDANT,-,RED CHICKEN,NaN,NaN,RECIFE,CLOSED,...,NaN,NaN,7/5/2010,17/3/2016,"R$ 50.000,00","R$ 15.000,00",R$ -,NaN,R$ -,SETTLEMENT
1,0000000-00.2011.0.00.0086,TAX,ACTIVE,DEFENDANT,-,RED CHICKEN,NaN,NaN,SÃO LUÍS,EXECUTION,...,NaN,NaN,3/3/2011,NaN,"R$ 180.000,00",NaN,"R$ 18.000,00","R$ 793.440,00",MEDIUM,NaN
2,0000000-00.2012.0.00.0092,TAX,ACTIVE,DEFENDANT,-,RED CHICKEN,NaN,NaN,SÃO LUÍS,EXECUTION,...,NaN,NaN,17/10/2012,NaN,"R$ 70.000,00",NaN,"R$ 7.000,00","R$ 266.980,00",MEDIUM,NaN
3,0000000-00.2013.0.00.0096,TAX,CLOSED,DEFENDANT,-,RED CHICKEN,NaN,NaN,FORTALEZA,CLOSED,...,NaN,NaN,17/12/2013,2/2/2017,"R$ 95.104,75","R$ 72.279,61",R$ -,NaN,R$ -,SETTLEMENT
4,0000000-00.2014.0.00.0097,TAX,CLOSED,DEFENDANT,-,RED CHICKEN,NaN,NaN,FORTALEZA,CLOSED,...,NaN,NaN,15/1/2014,5/12/2014,"R$ 29.000,00","R$ 5.800,00",R$ -,NaN,R$ -,SETTLEMENT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93,0000000-00.2020.0.00.0023,LABOR,ACTIVE,DEFENDANT,OWN,RED CHICKEN,-,CHEF,FORTALEZA,KNOWLEDGE,...,1/7/2020,101.0,6/6/2020,NaN,"R$ 80.396,00",NaN,"R$ 40.198,00","R$ 80.396,00",HIGH,NaN
94,0000000-00.2020.0.00.0057,LABOR,ACTIVE,DEFENDANT,THIRD,RED CHICKEN,BLUE'S CLEANING,CLEANING ASSISTANT,FORTALEZA,KNOWLEDGE,...,30/10/2019,100.0,10/6/2020,NaN,"R$ 50.000,00",NaN,R$ -,"R$ 50.000,00",LOW,NaN
95,0000000-00.2020.0.00.0010,LABOR,ACTIVE,DEFENDANT,OWN,RED BURGUER,-,CASHIER,NATAL,KNOWLEDGE,...,1/10/2019,101.0,13/6/2020,NaN,"R$ 60.000,00",NaN,"R$ 6.000,00","R$ 60.000,00",MEDIUM,NaN
96,0000000-00.2020.0.00.0059,LABOR,ACTIVE,DEFENDANT,THIRD,RED CHICKEN,BLUE'S CLEANING,CLEANING ASSISTANT,NATAL,KNOWLEDGE,...,26/12/2018,102.0,14/6/2020,NaN,"R$ 474.542,33",NaN,"R$ 47.454,23","R$ 474.542,33",MEDIUM,NaN
97,0000000-00.2020.0.00.0073,LABOR,ACTIVE,DEFENDANT,THIRD,RED CHICKEN,OREGON,TELEMARKETING ATTENDANT,NATAL,KNOWLEDGE,...,27/5/2020,108.0,19/6/2020,NaN,"R$ 40.000,00",NaN,"R$ 4.000,00","R$ 40.000,00",MEDIUM,NaN

In [10]:
dados.isnull().sum()

LAWSUIT NUMBER             0
AREA                       0
STATUS                     0
PLAINTIFF OR DEFENDANT     0
CONTRACT TYPE              0
COMPANY                    0
SUPPLIER NAME             16
TYPE OF POSITION          16
CITY SUBSIDIARIES          0
PHASE                      0
ADMISSION DATE            16
DISMISSAL DATE            16
ID PLANTIFF'S LAWYER      16
CLAIM START DATE           0
CLOSE DATE                84
CLAIM AMOUNT               0
AMOUNT PAID               84
 PROVISION VALUE           0
 RISK VALUE               14
RISK                       0
TYPE OF CLOSING CLAIM     84
dtype: int64

In [14]:
dados['RISK'].unique()

array([' R$ -   ', 'MEDIUM', 'LOW', 'HIGH'], dtype=object)